laser:
  workspace:
    x-size: 2438
    y-size: 1219
  motor-config:
    # .0032" = 0.08128 mm
    step-resolution: .0032
    step-distance-unit: inches
    x-pin: 21
    x-pin-dir: 22
    x-pin-endstop: 2
    y-pin: 24
    y-pin-dir: 25
    y-pin-endstop: 26
    step-mode: 32ND
    step-m0-pin: 14
    step-m1-pin: 15
    step-m2-pin: 13